server:
  port: 9903

zuul:
  routes:
    server:
      path: /server/**
      serviceId: server-service
      sensitiveHeaders: "*"
    web:
      path: /web/**
      serviceId: web-service
      sensitiveHeaders: "*"